/**
 * Agenda service.
 *
 * Responsabilidades:
 *  1. Definição do DTO que o backend retornará em /api/agenda
 *  2. Mock data realista (Abril/Maio 2026) para o período de desenvolvimento
 *  3. Função getAgenda() — pronta para trocar mock por chamada real ao backend
 *
 * Independente de React — sem imports de hooks ou JSX.
 */

import type { AgendaDTO, AgendaEventDTO } from '../interfaces/agenda.interfaces';

// ─── Mock data ─────────────────────────────────────────────────────────────────
// Simula o payload que o endpoint GET /api/agenda retornará,
// agregando eventos das empresas da watchlist do usuário.

const MOCK_EVENTS: AgendaEventDTO[] = [
  // ── Março 2026 (passado) ──────────────────────────────────────────────────
  {
    id: 'evt-001',
    ticker: 'CSAN3',
    companyName: 'Cosan',
    logoUrl: null,
    eventType: 'balanco',
    title: 'Resultado 4T25',
    date: '2026-03-26',
    description: 'Divulgação do resultado referente ao 4° trimestre de 2025. Receita, EBITDA e lucro líquido consolidados.',
    value: null,
    valueUnit: null,
    pillar: 'profitability',
    sourceLabel: 'CVM',
    sourceUrl: null,
    severity: 'medium',
  },
  {
    id: 'evt-002',
    ticker: 'CSAN3',
    companyName: 'Cosan',
    logoUrl: null,
    eventType: 'conference_call',
    title: 'Conference Call 4T25',
    date: '2026-03-27',
    description: 'Teleconferência com analistas e investidores sobre os resultados do 4° trimestre de 2025.',
    value: null,
    valueUnit: null,
    pillar: 'growth',
    sourceLabel: 'RI',
    sourceUrl: null,
    severity: 'low',
  },
  {
    id: 'evt-003',
    ticker: 'BBDC4',
    companyName: 'Bradesco',
    logoUrl: null,
    eventType: 'dividendo',
    title: 'Pagamento JCP — Mar/2026',
    date: '2026-03-31',
    description: 'Pagamento de Juros sobre Capital Próprio referente a março de 2026.',
    value: 0.0176,
    valueUnit: 'BRL/ação',
    pillar: 'dividends',
    sourceLabel: 'B3',
    sourceUrl: null,
    severity: 'medium',
  },

  // ── Abril 2026 (mês atual) ────────────────────────────────────────────────
  {
    id: 'evt-004',
    ticker: 'TAEE11',
    companyName: 'Taesa',
    logoUrl: null,
    eventType: 'ex_dividendo',
    title: 'Data Ex — JCP Abr/2026',
    date: '2026-04-07',
    description: 'Acionistas precisam estar posicionados até o fechamento do pregão de hoje para ter direito ao JCP de R$ 0,38 por unit.',
    value: 0.38,
    valueUnit: 'BRL/ação',
    pillar: 'dividends',
    sourceLabel: 'B3',
    sourceUrl: null,
    severity: 'medium',
  },
  {
    id: 'evt-005',
    ticker: 'PETR4',
    companyName: 'Petrobras',
    logoUrl: null,
    eventType: 'ex_dividendo',
    title: 'Data Ex — Dividendo',
    date: '2026-04-09',
    description: 'Data ex-dividendo da distribuição extraordinária referente ao exercício de 2025. DPA de R$ 0,52.',
    value: 0.52,
    valueUnit: 'BRL/ação',
    pillar: 'dividends',
    sourceLabel: 'B3',
    sourceUrl: null,
    severity: 'high',
  },
  {
    id: 'evt-006',
    ticker: 'WEGE3',
    companyName: 'WEG',
    logoUrl: null,
    eventType: 'balanco',
    title: 'Resultado 1T26',
    date: '2026-04-10',
    description: 'Divulgação do resultado consolidado do 1° trimestre de 2026. Expectativa de crescimento de receita acima de 15% YoY.',
    value: null,
    valueUnit: null,
    pillar: 'growth',
    sourceLabel: 'CVM',
    sourceUrl: null,
    severity: 'high',
  },
  {
    id: 'evt-007',
    ticker: 'WEGE3',
    companyName: 'WEG',
    logoUrl: null,
    eventType: 'conference_call',
    title: 'Conference Call 1T26',
    date: '2026-04-11',
    description: 'Teleconferência para discussão dos resultados do 1° trimestre de 2026 com analistas de mercado.',
    value: null,
    valueUnit: null,
    pillar: null,
    sourceLabel: 'RI',
    sourceUrl: null,
    severity: 'low',
  },
  {
    id: 'evt-008',
    ticker: 'BBAS3',
    companyName: 'Banco do Brasil',
    logoUrl: null,
    eventType: 'fato_relevante',
    title: 'Assembleia Geral Ordinária — AGO 2026',
    date: '2026-04-14',
    description: 'Assembleia para deliberação sobre distribuição de dividendos, eleição do conselho de administração e aprovação das demonstrações financeiras de 2025.',
    value: null,
    valueUnit: null,
    pillar: 'dividends',
    sourceLabel: 'CVM',
    sourceUrl: null,
    severity: 'medium',
  },
  {
    id: 'evt-009',
    ticker: 'FLRY3',
    companyName: 'Fleury',
    logoUrl: null,
    eventType: 'balanco',
    title: 'Resultado 1T26',
    date: '2026-04-14',
    description: 'Divulgação dos resultados consolidados do 1° trimestre de 2026.',
    value: null,
    valueUnit: null,
    pillar: 'profitability',
    sourceLabel: 'CVM',
    sourceUrl: null,
    severity: 'medium',
  },
  {
    id: 'evt-010',
    ticker: 'TAEE11',
    companyName: 'Taesa',
    logoUrl: null,
    eventType: 'dividendo',
    title: 'Pagamento JCP Abr/2026',
    date: '2026-04-18',
    description: 'Pagamento de Juros sobre Capital Próprio aos acionistas posicionados antes da data ex de 07/04.',
    value: 0.38,
    valueUnit: 'BRL/ação',
    pillar: 'dividends',
    sourceLabel: 'B3',
    sourceUrl: null,
    severity: 'medium',
  },
  {
    id: 'evt-011',
    ticker: 'VALE3',
    companyName: 'Vale',
    logoUrl: null,
    eventType: 'fato_relevante',
    title: 'Produção e Vendas 1T26',
    date: '2026-04-22',
    description: 'Divulgação do relatório de produção e vendas referente ao 1° trimestre de 2026. Indicadores de volume de minério de ferro e pelotas.',
    value: null,
    valueUnit: null,
    pillar: 'growth',
    sourceLabel: 'CVM',
    sourceUrl: null,
    severity: 'high',
  },
  {
    id: 'evt-012',
    ticker: 'PETR4',
    companyName: 'Petrobras',
    logoUrl: null,
    eventType: 'dividendo',
    title: 'Pagamento Dividendo',
    date: '2026-04-22',
    description: 'Pagamento da distribuição extraordinária aos acionistas posicionados antes da data ex de 09/04.',
    value: 0.52,
    valueUnit: 'BRL/ação',
    pillar: 'dividends',
    sourceLabel: 'B3',
    sourceUrl: null,
    severity: 'high',
  },
  {
    id: 'evt-013',
    ticker: 'VALE3',
    companyName: 'Vale',
    logoUrl: null,
    eventType: 'balanco',
    title: 'Resultado 1T26',
    date: '2026-04-24',
    description: 'Divulgação do resultado consolidado do 1° trimestre de 2026. Expectativa de mercado: receita de R$ 62bi, EBITDA de R$ 28bi.',
    value: null,
    valueUnit: null,
    pillar: 'profitability',
    sourceLabel: 'CVM',
    sourceUrl: null,
    severity: 'high',
  },
  {
    id: 'evt-014',
    ticker: 'VALE3',
    companyName: 'Vale',
    logoUrl: null,
    eventType: 'conference_call',
    title: 'Conference Call 1T26',
    date: '2026-04-25',
    description: 'Teleconferência com analistas e investidores sobre os resultados do 1° trimestre de 2026.',
    value: null,
    valueUnit: null,
    pillar: null,
    sourceLabel: 'RI',
    sourceUrl: null,
    severity: 'low',
  },
  {
    id: 'evt-015',
    ticker: 'ITUB4',
    companyName: 'Itaú Unibanco',
    logoUrl: null,
    eventType: 'balanco',
    title: 'Resultado 1T26',
    date: '2026-04-28',
    description: 'Divulgação do resultado do 1° trimestre de 2026. Expectativa de lucro líquido recorrente acima de R$ 10bi.',
    value: null,
    valueUnit: null,
    pillar: 'profitability',
    sourceLabel: 'CVM',
    sourceUrl: null,
    severity: 'high',
  },
  {
    id: 'evt-016',
    ticker: 'BBAS3',
    companyName: 'Banco do Brasil',
    logoUrl: null,
    eventType: 'balanco',
    title: 'Resultado 1T26',
    date: '2026-04-30',
    description: 'Divulgação dos resultados do 1° trimestre de 2026.',
    value: null,
    valueUnit: null,
    pillar: 'profitability',
    sourceLabel: 'CVM',
    sourceUrl: null,
    severity: 'high',
  },

  // ── Maio 2026 (próximo mês) ───────────────────────────────────────────────
  {
    id: 'evt-017',
    ticker: 'BBAS3',
    companyName: 'Banco do Brasil',
    logoUrl: null,
    eventType: 'conference_call',
    title: 'Conference Call 1T26',
    date: '2026-05-05',
    description: 'Teleconferência com analistas sobre os resultados do 1° trimestre de 2026.',
    value: null,
    valueUnit: null,
    pillar: null,
    sourceLabel: 'RI',
    sourceUrl: null,
    severity: 'low',
  },
  {
    id: 'evt-018',
    ticker: 'ITUB4',
    companyName: 'Itaú Unibanco',
    logoUrl: null,
    eventType: 'conference_call',
    title: 'Conference Call 1T26',
    date: '2026-05-05',
    description: 'Teleconferência com analistas sobre os resultados do 1° trimestre de 2026.',
    value: null,
    valueUnit: null,
    pillar: null,
    sourceLabel: 'RI',
    sourceUrl: null,
    severity: 'low',
  },
  {
    id: 'evt-019',
    ticker: 'BBDC4',
    companyName: 'Bradesco',
    logoUrl: null,
    eventType: 'ex_dividendo',
    title: 'Data Ex — JCP Mai/2026',
    date: '2026-05-07',
    description: 'Data ex para o JCP de R$ 0,0176 por ação ordinária e preferencial.',
    value: 0.0176,
    valueUnit: 'BRL/ação',
    pillar: 'dividends',
    sourceLabel: 'B3',
    sourceUrl: null,
    severity: 'medium',
  },
  {
    id: 'evt-020',
    ticker: 'WEGE3',
    companyName: 'WEG',
    logoUrl: null,
    eventType: 'dividendo',
    title: 'Pagamento Dividendos 1T26',
    date: '2026-05-12',
    description: 'Pagamento de dividendos referentes ao 1° trimestre de 2026.',
    value: 0.18,
    valueUnit: 'BRL/ação',
    pillar: 'dividends',
    sourceLabel: 'B3',
    sourceUrl: null,
    severity: 'medium',
  },
  {
    id: 'evt-021',
    ticker: 'ABEV3',
    companyName: 'Ambev',
    logoUrl: null,
    eventType: 'balanco',
    title: 'Resultado 1T26',
    date: '2026-05-08',
    description: 'Divulgação dos resultados do 1° trimestre de 2026.',
    value: null,
    valueUnit: null,
    pillar: 'profitability',
    sourceLabel: 'CVM',
    sourceUrl: null,
    severity: 'medium',
  },
  {
    id: 'evt-022',
    ticker: 'BBDC4',
    companyName: 'Bradesco',
    logoUrl: null,
    eventType: 'dividendo',
    title: 'Pagamento JCP — Mai/2026',
    date: '2026-05-31',
    description: 'Pagamento de Juros sobre Capital Próprio referente a maio de 2026.',
    value: 0.0176,
    valueUnit: 'BRL/ação',
    pillar: 'dividends',
    sourceLabel: 'B3',
    sourceUrl: null,
    severity: 'medium',
  },
  {
    id: 'evt-023',
    ticker: 'TAEE11',
    companyName: 'Taesa',
    logoUrl: null,
    eventType: 'balanco',
    title: 'Resultado 1T26',
    date: '2026-05-14',
    description: 'Divulgação do resultado consolidado do 1° trimestre de 2026.',
    value: null,
    valueUnit: null,
    pillar: 'profitability',
    sourceLabel: 'CVM',
    sourceUrl: null,
    severity: 'medium',
  },
];

// ─── Chamada HTTP ──────────────────────────────────────────────────────────────

/**
 * Retorna a agenda do usuário.
 *
 * TODO: substituir o mock pelo endpoint real:
 *   return apiFetch<AgendaDTO>('/api/agenda', {}, token);
 */
export async function getAgenda(_token?: string | null): Promise<AgendaDTO> {
  // Simula latência de rede
  await new Promise((resolve) => setTimeout(resolve, 600));

  return {
    events: MOCK_EVENTS,
    generatedAt: new Date().toISOString(),
  };
}
